spring.profiles.active=local

# Database Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smarttask_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server Port
server.port=${SERVER_PORT:8080}

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


spring.application.name=smarttask-api
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

groq.api.key=${GROQ_API_KEY:}
groq.model=${GROQ_MODEL:llama-3.3-70b-versatile}

spring.jpa.open-in-view=false


spring.mail.host=${SMARTTASK_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SMARTTASK_MAIL_PORT:587}
spring.mail.username=${SMARTTASK_MAIL_USERNAME:}
spring.mail.password=${SMARTTASK_MAIL_PASSWORD:}
spring.mail.properties.mail.smtp.auth=${SMARTTASK_MAIL_SMTP_AUTH:true}
spring.mail.properties.mail.smtp.starttls.enable=${SMARTTASK_MAIL_SMTP_STARTTLS:true}
